name: hugo deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: hugo-deploy-gh-pages
        uses: linuxsuren/surenpi@master
        env:
          GIT_DEPLOY_KEY: ${{ secrets.HUGO_DEPLOY }}
          HUGO_VERSION: "0.82.0"
          WEBSITE_GIT: "git@github.com:ajtl/ajtl.github.io.git"
          WEBSITE_DIR: "ajtl.github.io"