# .github/workflows/deploy.yml
name: Deploy
  push:
    branches: [main]


jobs:
  hugo_deploy:
    name: Hugo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          depth: 1
          submodules: true
          token: ${{ secrets.HUGO_DEPLOY }}

      - uses: K-Phoen/hugo-gh-pages-action@master
        with:
          github_token: ${{ secrets.HUGO_DEPLOY }}
          hugo_version: 0.82.0
          build_folder: "docs"
          build_branch: "main"

