name: hugo deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          TARGET_REPO: ajtl/ajtl.github.io
          TARGET_BRANCH: main
          TOKEN: ${{ secrets.HUGO_DEPLOY }}