# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    uses: actions/checkout@v2
    with:
    # Repository name with owner. For example, actions/checkout
    # Default: ${{ github.repository }}
      repository: ${{ github.ajtl.github.io }}

    # The branch, tag or SHA to checkout. When checking out the repository that
    # triggered a workflow, this defaults to the reference or SHA for that event.
    # Otherwise, uses the default branch.
      ref: main

    # Personal access token (PAT) used to fetch the repository. The PAT is configured
    # with the local git config, which enables your scripts to run authenticated git
    # commands. The post-job step removes the PAT.
    #
    # We recommend using a service account with the least permissions necessary. Also
    # when generating a new PAT, select the least scopes necessary.
    #
    # [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    #
    # Default: ${{ github.token }}
      token: ${{ secrets.HUGO_DEPLOY }}

     
    # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
    # recursively checkout submodules.
    #
    # When the `ssh-key` input is not provided, SSH URLs beginning with
    # `git@github.com:` are converted to HTTPS.
    #
    # Default: false
      submodules: true
  steps:
    - name: 'Building...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: ajtl/ajtl.github.io
        DEPLOY_BRANCH: main
        DEPLOY_KEY: ${{ secrets.HUGO_DEPLOY }}
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: Asia/Shanghai